---
title: "k-means clustering with penguins"
author: "Allison Horst"
date: "6/26/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidymodels)
library(palmerpenguins)
library(GGally)
library(shadowtext)
library(NbClust)
library(patchwork)
library(kableExtra)
library(mclust)
knitr::opts_chunk$set(echo = TRUE)
```

Following exactly along with: https://www.tidymodels.org/learn/statistics/k-means/

Using `kmeans()`: 

Example 1: Male penguins bill dimensions
```{r}
mp_bills <- penguins %>% 
  filter(sex == "male") %>% 
  select(species, bill_length_mm, bill_depth_mm)

mp_bills_nospecies <- mp_bills %>% 
  select(-species) %>% 
  scale() %>% 
  as.data.frame()

# Perform k-means on male penguin bill dimensions (k = 3, w/20 centroid starts)
mp_bills_kmeans <- kmeans(mp_bills_nospecies, centers = 3, nstart = 20)
mp_bills_kmeans

# Bind clusters to the data
mp_kmeans_clusters <- cbind(mp_bills_nospecies, cluster = mp_bills_kmeans$cluster, species = mp_bills$species)

ggplot(mp_kmeans_clusters, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_text(aes(label = cluster, color = species))

male_cluster_counts <- mp_kmeans_clusters %>% 
  complete() %>% 
  count(species, cluster) %>% 
  pivot_wider(names_from = species, values_from = n)

male_cluster_counts
# SERIOUSLY WTF...those 3s are NOT closer to the 3 centroid...
# 
# plot(mp_bills_nospecies, col = mp_bills_kmeans$cluster)
# points(mp_bills_kmeans$centers, col = 1:2, pch = 8, cex = 2)
# 
# # Testing some tidymodels methods instead...
# test_cluster <- augment(mp_bills_kmeans, mp_bills_nospecies) %>% 
#   rename(cluster_number = .cluster)
# 
# ggplot(data = test_cluster, aes(x = bill_length_mm, y = bill_depth_mm, color = cluster_number)) +
#   geom_point()
```

# With all penguins (bill dimensions)

Example 2: All penguins bill dimensions
```{r}
p_bills <- penguins %>% 
  select(species, bill_length_mm, bill_depth_mm) %>% 
  drop_na()

p_bills_nospecies <- p_bills %>% 
  select(-species) %>% 
  scale() %>% 
  as.data.frame()

# Perform k-means on male penguin bill dimensions (k = 3, w/20 centroid starts)
p_bills_kmeans <- kmeans(p_bills_nospecies, centers = 3, nstart = 20)
p_bills_kmeans

# Bind clusters to the data
p_kmeans_clusters <- cbind(p_bills_nospecies, cluster = p_bills_kmeans$cluster, species = p_bills$species)

ggplot(p_kmeans_clusters, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_text(aes(label = cluster, color = species))

p_cluster_counts <- p_kmeans_clusters %>% 
  complete() %>% 
  count(species, cluster) %>% 
  pivot_wider(names_from = species, values_from = n)

p_cluster_counts
```




# Trying EM using `mclust` package for fun

See: https://en.wikibooks.org/wiki/Data_Mining_Algorithms_In_R/Clustering/Expectation_Maximization_%28EM%29#Executing_the_Algorithm

```{r}
BIC <- mclustBIC(mp_bills_nospecies)
plot(BIC)
summary(BIC)

mod1 <- Mclust(mp_bills_nospecies, G = 3, x = BIC)
summary(mod1, parameters = TRUE)

plot(mod1, what = "classification")
```



