---
title: 'Palmer Penguins manuscript code'
output:
  html_document:
    number_sections: yes
  pdf_document: default
bibliography: ../bibliography/references.bib
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)
library(palmerpenguins)
library(kableExtra)
library(patchwork)
library(gt)
library(GGally)
library(recipes)
library(shadowtext)
library(broom)
knitr::opts_chunk$set(echo = TRUE)

theme_set(theme_minimal())
```

# MANUSCRIPT CODE

## Structure and sample size 

```{r, iris-table, echo = FALSE}
set.seed(1900)
sample_n(iris, 6) %>% 
  kable(caption = "Six randomly selected rows from the iris dataset (of 150 total rows). Values for petal and sepal dimensions are in centimeters.")
```

```{r, penguins-table}
set.seed(1900)
sample_n(penguins, 6) %>% 
  kable(caption = "Six randomly selected rows from the penguins dataset (of 344 total rows). Units of the four numeric penguin measurements are included as suffixes in variable names, with \"_mm\" indicating millimeters, and \"_g\" indicating grams.")
```

```{r compare_counts, echo = FALSE}

iris_counts <- iris %>% 
  count(Species) %>% 
  rename(`Iris species` = Species)

penguin_counts <- penguins %>% 
  mutate(species = as.character(species)) %>% 
  mutate(species = case_when(
    species == "Adelie" ~ "Adélie", 
    TRUE ~ species
  )) %>% 
  mutate(sex = str_to_title(sex)) %>% 
  group_by(species, sex) %>% 
  tally() %>% 
  pivot_wider(names_from = sex, values_from = n) %>% 
  replace_na(list(`NA` = 0)) %>% 
  as.data.frame() %>% 
  rename(`Penguin species` = species)


iris_penguin_n <- cbind(iris_counts, penguin_counts) %>%
   rename(`Sample size` = n)

 iris_penguin_n %>%
   gt() %>%
   tab_spanner(
     label = "Iris sample size (by species)",
     columns = vars(`Iris species`, `Sample size`)
   ) %>%
   tab_spanner(
     label = "Penguin sample size (by species and sex)",
     columns = vars(`Penguin species`, `Female`, `Male`, `NA`)
   ) %>%
   tab_footnote(
     footnote = "Note: Here, penguin sample sizes are split by species and sex, and could be further divided by island and year. NA column for penguins indicate observations where sex was not recorded.",
     location = cells_column_labels(
       columns = vars(`Penguin species`)
     )
   )
```

## Overview comparison: numeric variables

```{r, warning = FALSE, message = FALSE, echo = FALSE, fig.align = "center"}
penguins %>%
  select(species, where(is.numeric)) %>% 
  ggpairs(aes(color = species, shape = species),
          columns = c("flipper_length_mm", "body_mass_g", 
                      "bill_length_mm", "bill_depth_mm"),
          columnLabels = c("Flipper length (mm)","Body mass (g)", "Bill length (mm)", "Bill depth (mm)"),
          upper = list(continuous = wrap("cor", size = 3))) +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  scale_color_manual(values = c("darkorange","purple","cyan4")) +
  scale_shape_manual(values = c(15,16,17)) +
  theme_minimal() +
  theme(
        text = element_text(size = 10, family = "Arial"),
        panel.grid.major = element_line(colour = NA),
        panel.grid.minor = element_blank(),
        panel.border = element_rect(color = "gray80", fill = NA)
        )

ggsave(here("figures","penguins_ggpairs.png"), height = 5, width = 9)

iris %>%
  ggpairs(aes(color = Species),
          columns = c("Petal.Length", "Petal.Width", 
                      "Sepal.Length", "Sepal.Width"),
          columnLabels = c("Petal length (cm)","Petal width (cm)", "Sepal length (cm)", "Sepal width (cm)"),
          upper = list(continuous = wrap("cor", size = 3))) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) +
  scale_fill_manual(values = c("darkorange","purple","cyan4")) +
  theme_minimal() +
  theme(
        text = element_text(size = 10, family = "Arial"),
        panel.grid.major = element_line(colour = NA),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "gray90", color = "gray90")
        )

ggsave(here("figures","iris_ggpairs.png"), height = 5, width = 9)

```

## Linear correlation & regression

```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center"}

penguin_flip_mass_scatter <- ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(aes(color = species, shape = species), size = 1.5, alpha = 0.5) +
  geom_smooth(method = "lm", aes(group = species, color = species), se = FALSE, show.legend = FALSE) +
  theme_minimal() +
  scale_color_manual(values = c("darkorange","darkorchid","cyan4")) +
  theme(legend.position = "bottom") +
  labs(x = "Flipper length (mm)", 
       y = "Body mass (g)") +
  theme(plot.title.position = "plot",
        panel.border = element_rect(fill = NA, color = "gray70"))

penguin_flip_mass_scatter_all <- ggplot(penguins, aes(x = flipper_length_mm, y = body_mass_g)) +
  geom_point(color = "gray50", size = 1.5, alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  theme_minimal() +
  labs(x = "Flipper length (mm)", 
       y = "Body mass (g)") +
  theme(plot.title.position = "plot",
        panel.border = element_rect(fill = NA, color = "gray70"))

iris_petal_scatter <- ggplot(iris, aes(x = Petal.Length, y = Petal.Width)) +
  geom_point(aes(color = Species, size = Species, shape = Species), size = 1.5, alpha = 0.5) +
  geom_smooth(aes(group = Species, color = Species), method = "lm", se = FALSE, show.legend = FALSE) +
  theme_minimal() +
  scale_color_manual(values = c("darkorange","darkorchid","cyan4")) +
  theme(legend.position = "bottom") +
  labs(x = "Petal length (cm)",
       y = "Petal width (cm)") +
  theme(plot.title.position = "plot",
        panel.background = element_rect(fill = "gray90", color = "gray90"))

iris_petal_scatter_all <- ggplot(iris, aes(x = Petal.Length, y = Petal.Width)) +
  geom_point(color = "gray50", size = 1.5, alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  theme_minimal() +
  labs(x = "Petal length (cm)",
       y = "Petal width (cm)") +
  theme(plot.title.position = "plot",
        panel.background = element_rect(fill = "gray90", color = "gray90")) 

(penguin_flip_mass_scatter_all + iris_petal_scatter_all) / (penguin_flip_mass_scatter + iris_petal_scatter) + plot_annotation(tag_levels = 'A')

ggsave(here("figures","iris_penguins_scatter.png"), height = 6, width = 8)

# Simpson's Paradox example (bill dimensions)
simpson_nospecies <- ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(color = "gray40", alpha = 0.6, size = 2) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +
  theme_minimal() +
  theme(panel.border = element_rect(fill = NA, color = "gray70")) +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)")

simpson_wspecies <- ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm, group = species)) +
  geom_point(aes(color = species, shape = species), size = 2, alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE, aes(color = species)) +
  scale_color_manual(values = c("darkorange","darkorchid","cyan4")) +
  theme_minimal() +
  theme(panel.border = element_rect(fill = NA, color = "gray70"),
        legend.position = c(0.16,0.14)) +
  labs(x = "Bill length (mm)", y = "Bill depth (mm)")

simpson_gg <- (simpson_nospecies | simpson_wspecies) + plot_annotation(tag_levels = 'A')

simpson_gg

ggsave(here("figures","simpson_gg.png"), width = 8, height = 4)
```

## PCA

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.align = "center"}
# Copied from Alison Hill's post! 

### PENGUINS PCA: 
penguin_recipe <-
  recipe(~., data = penguins) %>% 
  update_role(species, island, sex, new_role = "id") %>% 
  step_naomit(all_predictors()) %>% 
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors(), id = "pca") %>% 
  prep()

penguin_pca <- 
  penguin_recipe %>% 
  tidy(id = "pca") 

penguin_percvar <- penguin_recipe %>% 
  tidy(id = "pca", type = "variance") %>% 
  dplyr::filter(terms == "percent variance") 

# penguin_pca

# Biplot: 

# get pca loadings into wider format
pca_wider <- penguin_pca %>% 
  tidyr::pivot_wider(names_from = component, id_cols = terms)

# define arrow style:
arrow_style <- arrow(length = unit(.05, "inches"),
                     type = "closed")

# Make the biplot:
pca_plot <-
  juice(penguin_recipe) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = species, shape = species), 
             alpha = 0.5, 
             size = 2) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) 

penguins_biplot <- pca_plot +
  geom_segment(data = pca_wider,
               aes(xend = PC1, yend = PC2), 
               x = 0, 
               y = 0, 
               arrow = arrow_style) + 
  geom_shadowtext(data = pca_wider,
            aes(x = PC1, y = PC2, label = terms), 
            nudge_x = c(0.7,0.7,1.7,1.2), 
            nudge_y = c(-0.1,-0.2,0.1,-0.1),
            size = 4, 
            color = "black",
            bg.color = "white") +
  theme(legend.position = "bottom",
        panel.border = element_rect(color = "gray70", fill = NA))

# For positioning (above): 
# 1: bill_length
# 2: bill_depth
# 3: flipper length
# 4: body mass

penguin_screeplot <- penguin_percvar %>% 
  ggplot(aes(x = component, y = value)) + 
  geom_col(fill = "gray50") + 
  scale_x_continuous(limits = c(0, 5), expand = c(0,0)) + 
  scale_y_continuous(limits = c(0,100), expand = c(0,0)) +
  ylab("% of total variance") +
  geom_text(aes(label = round(value,2)), vjust=-0.25) +
  theme(panel.border = element_rect(color = "gray70", fill = NA))

### IRIS PCA: 
iris_recipe <-
  recipe(~., data = iris) %>% 
  update_role(Species, new_role = "id") %>% 
  step_normalize(all_predictors()) %>%
  step_pca(all_predictors(), id = "pca") %>% 
  prep()

iris_pca <- 
  iris_recipe %>% 
  tidy(id = "pca") 

# Biplot: 

# get pca loadings into wider format
iris_wider <- iris_pca %>% 
  tidyr::pivot_wider(names_from = component, id_cols = terms)

# define arrow style:
arrow_style <- arrow(length = unit(.05, "inches"),
                     type = "closed")

# Make the biplot:
iris_pca_plot <-
  juice(iris_recipe) %>%
  ggplot(aes(PC1, PC2)) +
  geom_point(aes(color = Species, shape = Species), 
             alpha = 0.5, 
             size = 2) +
  scale_colour_manual(values = c("darkorange","purple","cyan4")) 

iris_biplot <- iris_pca_plot +
  geom_segment(data = iris_wider,
               aes(xend = PC1, yend = PC2), 
               x = 0, 
               y = 0, 
               arrow = arrow_style) + 
  geom_shadowtext(data = iris_wider,
            aes(x = PC1, y = PC2, label = terms), 
            nudge_x = c(0.5,0.3,1,1.2), 
            nudge_y = c(-0.1,-0.2,0.1,-0.1),
            size = 4, 
            color = "black",
            bg.color = "white") +
  theme(panel.background = element_rect(fill = "gray90", color = "gray90"),
        legend.position = "bottom")

iris_percvar <- iris_recipe %>% 
  tidy(id = "pca", type = "variance") %>% 
  dplyr::filter(terms == "percent variance")

iris_screeplot <- iris_percvar %>% 
  ggplot(aes(x = component, y = value)) + 
  geom_col(fill = "gray50") + 
  scale_x_continuous(limits = c(0, 5), expand = c(0,0)) + 
  scale_y_continuous(limits = c(0,100), expand = c(0,0)) +
  ylab("% of total variance") +
  geom_text(aes(label = round(value,2)), vjust=-0.25) +
  theme(panel.background = element_rect(fill = "gray90", color = "gray90"))

(penguins_biplot | iris_biplot) / (penguin_screeplot | iris_screeplot) + plot_annotation(tag_levels = 'A')

ggsave(here("figures","pca_plots.png"), width = 8, height = 8)
```

## K-means clustering

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.align = "center"}
# TWO VARIABLE k-means comparison
# Penguins: Bill length vs. bill depth
# Iris: petal length vs. petal width

pb_species <- penguins %>% 
  select(species, starts_with("bill")) %>% 
  drop_na()

pb_nospecies <- pb_species %>% 
  select(-species) %>% 
  recipe() %>% 
  step_normalize(all_numeric()) %>% 
  prep() %>% 
  juice()
  
# Perform k-means on penguin bill dimensions (k = 3, w/20 centroid starts)
# save augmented data
pb_clust <- 
  pb_nospecies %>% 
  kmeans(centers = 3, nstart = 20) %>% 
  broom::augment(pb_species)

# Plot clusters
pb_kmeans_gg <- 
  pb_clust %>% 
  ggplot(aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_text(aes(label = .cluster, color = species),
            key_glyph = draw_key_rect) +
  theme(legend.position = "bottom") +
  scale_color_manual(values = c("darkorange","darkorchid","cyan4"))

# Get counts in each cluster by species
pb_clust_n <- pb_clust %>% 
  count(species, .cluster) %>% 
  pivot_wider(names_from = species, values_from = n, names_sort = TRUE) %>% 
  arrange(.cluster)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center"}

ip_species <- iris %>% 
  select(Species, starts_with("Petal"))

# remove species factor & scale petal dimensions: 
ip_nospecies <- ip_species %>% 
  select(-Species) %>% 
  recipe() %>% 
  step_normalize(all_numeric()) %>% 
  prep() %>% 
  juice()

# Perform k-means on iris petal dimensions (k = 3, w/20 centroid starts)
ip_clust <- 
  ip_nospecies %>% 
  kmeans(centers = 3, nstart = 20) %>% 
  broom::augment(ip_species)

# Plot clusters
ip_kmeans_gg <- 
  ip_clust %>% 
  ggplot(aes(x = Petal.Length, y = Petal.Width)) +
  geom_text(aes(label = .cluster, color = Species), 
            key_glyph = draw_key_rect) +
  theme(legend.position = "bottom",
         panel.background = element_rect(fill = "gray92", color = "gray90")) +
  scale_color_manual(values = c("darkorange","darkorchid","cyan4")) 

# Get counts in each cluster by species
ip_clust_n <- ip_clust %>% 
  count(Species, .cluster) %>% 
  pivot_wider(names_from = Species, values_from = n, names_sort = TRUE) %>% 
  arrange(.cluster)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.align = "center"}
(pb_kmeans_gg | ip_kmeans_gg) + plot_annotation(tag_levels = "A")

kmeans_2var_table <- cbind(pb_clust_n, ip_clust_n) %>% 
  kable() %>% 
  kable_styling(full_width = FALSE) %>% 
  column_spec(c(5:8), background = "gainsboro") %>% 
  add_header_above(c("Penguins cluster assignments" = 4, "Iris cluster assignments" = 4))

kmeans_2var_table
```

